algoritmo "semnome"
// Função :
// Autor :
// Data : 06/12/2023
// Seção de Declarações Desenvolva um algoritmo que receba um número e diga
// se este número está no intervalo entre 100 e 200.
var
numero: inteiro

inicio
escreval(" digite um numero: ")
leia(numero)
se (numero >= 100) e (numero <=200) entao
escreval(" numero esta no intervalo entre 100 e 200")
senao
escreval("numero nao esta no intervalo entre 100 e 200")

fimse
fimalgoritmo
