algoritmo "se entao senao"


var
Nome: caracter
nota1,nota2,media: real

inicio
escreval("digite o nome do aluno")
leia(Nome)
escreval("digite a nota do aluno")
leia(nota1)
escreval("digite a nota do aluno")
leia(nota2)
media:=(nota1+nota2)/2
escreval("media e =", media)
se media >=7 entao
escreva( nome," esta aprovado")
senao
escreval(nome," deve comparecer na coordenação do seu curso")
fimse
fimalgoritmo

